services:
  -
    service: consul
    display_name: Consul
    display_version: 1.4.2
    image: consul:1.4.2
  -
    service: vault
    display_name: Vault
    display_version: 1.0.3
    image: vault:1.0.3
  -
    service: redis
    display_name: Redis
    display_version: 5.0.x
    image: redis:5-alpine3.9
  -
    service: cassandra
    display_name: Cassandra
    display_version: 3.11.3
    image: cassandra:nfv-custom-3.11.3
    build_args:
      cassandra_version: 3.11.3
      lucene_version: 3.11.3.0
  -
    service: zookeeper
    display_name: Confluent-ZooKeeper
    display_version: 5.0.3
    image: confluentinc/cp-zookeeper:5.0.3
    
  -
    service: kafka
    display_name: Confluent-Kafka
    display_version: 5.0.3
    image: confluentinc/cp-enterprise-kafka:5.0.3

  -
    service: cpcc #cp-control-center
    display_name: Confluent-Control-Center
    display_version: 5.0.3
    image: confluentinc/cp-enterprise-control-center:5.0.3

  -
    service: es
    display_name: ElasticSearch
    display_version: 6.6.0
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0

post_start:
  - post_start_vault
  - post_start_cassandra
  - post_start_cpcc


    